### ISSUE TITLE
[4.4.0] Android init: Creating external cache directory failed

### ISSUE THREAD

**Issue by SkaterDad** [AGulev/DefUnityAds#29]
Defold 1.3.6
DefVideoAds 4.4.0

Google Pixel 6a
Android 13

Exception is thrown during initialization, preventing Unity Ads from working.

```
09-22 21:57:12.309 31492 31540 E UnityAds: com.unity3d.services.core.cache.CacheDirectory.getCacheDirectory() (line:38) :: Creating external cache directory failed: Attempt to invoke virtual method 'java.io.File android.content.Context.getExternalCacheDir()' on a null object reference
09-22 21:57:12.310 31492 31540 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getFilesDir()' on a null object reference
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.core.cache.CacheDirectory.getCacheDirectory(CacheDirectory.java:54)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.core.properties.SdkProperties.getCacheDirectory(SdkProperties.java:198)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.core.properties.SdkProperties.getCacheDirectory(SdkProperties.java:190)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.core.properties.SdkProperties.getLocalConfigurationFilepath(SdkProperties.java:174)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.core.configuration.ConfigurationReader.getLocalConfiguration(ConfigurationReader.java:34)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.core.configuration.ConfigurationReader.getCurrentConfiguration(ConfigurationReader.java:21)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.ads.operation.load.LoadModuleDecoratorTimeout.<init>(LoadModuleDecoratorTimeout.java:25)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.ads.operation.load.LoadModule.getInstance(LoadModule.java:35)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.services.ads.UnityAdsImplementation.load(UnityAdsImplementation.java:171)
09-22 21:57:12.310 31492 31540 W System.err:    at com.unity3d.ads.UnityAds.load(UnityAds.java:281)
09-22 21:57:12.310 31492 31540 W System.err:    at com.agulev.defunityads.DefUnityAdsJNI.load(DefUnityAdsJNI.java:235)
09-22 21:57:12.311 31492 31540 D UnityAds: com.unity3d.services.ads.UnityAdsImplementation.initialize() (line:63) :: ENTERED METHOD
09-22 21:57:12.311 31492 31540 D UnityAds: com.unity3d.services.UnityServices.initialize() (line:35) :: ENTERED METHOD
09-22 21:57:12.311 31492 31540 I UnityAds: com.unity3d.services.UnityServices.initialize() (line:119) :: Initializing Unity Services 4.4.0 (4400) with game id 3530625 in production mode
09-22 21:57:12.311 31492 31540 E UnityAds: com.unity3d.services.core.configuration.EnvironmentCheck.testCacheDirectory() (line:49) :: Unity Ads cache directory check fail: no working cache directory available
09-22 21:57:12.311 31492 31540 E UnityAds: com.unity3d.services.UnityServices.initialize() (line:133) :: Error during Unity Services environment check, halting Unity Services init
```

**Comment by AGulev** [comment]
Can't reproduce the issue using the extension example (Pixel 4a, Android 13 the latest [beta](https://developer.android.com/about/versions/13/get-qpr) )
Do you reproduce it using the example or maybe in your game?
If it's in you game what the other dependencies you have?
Could you try to create a minimal repo case?

**Comment by SkaterDad** [comment]
The bug you linked related to Android 13 in the other issue must be a frustrating one.   It certainly makes me hesistant o release any updates.

I will try to reproduce the issue using the demo project this evening and will let you know how it goes.

Here's my dependency list for the game:

```
dependencies#0 = https://github.com/rgrams/rendercam/archive/refs/tags/1.0.3.zip
dependencies#1 = https://github.com/AGulev/DefVideoAds/archive/refs/tags/4.4.0.zip
dependencies#2 = https://github.com/defold/extension-gpgs/archive/refs/tags/2.5.1.zip
dependencies#3 = https://github.com/subsoap/defsave/archive/refs/tags/v1.2.4.zip
dependencies#4 = https://github.com/defold/extension-iap/archive/refs/tags/4.0.0.zip
dependencies#5 = https://github.com/SkaterDad/extension-review/archive/refs/heads/update-android-lib.zip
dependencies#6 = https://github.com/subsoap/defglot/archive/refs/heads/master.zip
```

**Comment by AGulev** [comment]
I'll try to repo it using your dependencies

**Comment by AGulev** [comment]
@SkaterDad I can't reproduce it on my Pixel 4a
pls, try to repo the issue using the extension's example project

**Comment by AGulev** [comment]
@SkaterDad according to your log it seems like you call `load` method before ads initialization
could you pls check that?

**Comment by AGulev** [comment]
yes, I'm right here.
I can repo the same issue if I call 
unityads.load(INTERSTITIAL)
before 
unityads.initialize()

pls check your code

**Comment by SkaterDad** [comment]
Thanks for looking again.  I'll review the code again add some logging to test your theory.

**Comment by SkaterDad** [comment]
@AGulev You were correct.

It seems I was initializing the Unity ads in my GUI script, but calling load in my main.script `init()`, in the code I used to reset my game state.

I have added `unityads.is_initialized()` checks before I call `load` now, and it works great.

Appreciate your help and this great library 😀
